image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew
  - sudo apt-get update
  - sudo apt-get install -y google-chrome-stable
  - refreshenv

build_script:
  - ./gradlew test -Dselenide.headless=true --info
